# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95f105efcb853a7f7fd128aefa7dff4850446f0ccd4c62583362c72c72a477e94f1ffd01ac117cd3332b9a4309dc7405e710515b5ac6dfd76c6f01c951b4156e

test:
  secret_key_base: f41666ecd78e50fe932fd8182fc55954a57adf2b1196db61e88a5d931c428286fa27467a50ed33df05f4e1638f64d839c7bf9a41d678679c627966e2da0245f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
